---
- name: Install clipster
  yaourt:
    name: clipster

- name: Configure clipster service file
  template:
    src: clipster.service.j2
    dest: '{{ config_home }}/systemd/user/clipster.service'

- name: Enable clipster service
  systemd:
    name: clipster.service
    user: yes
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: '{{ user_xdg_runtime_dir }}'
    DBUS_SESSION_BUS_ADDRESS: '{{ user_dbus_session_bus_address }}'
    HOME: '{{ user_dir }}'
  become_user: root
