---
- name: Install redshift
  pacman:
    name: redshift
  become_user: root

- name: Configure redshift
  template:
    src: redshift.conf.j2
    dest: '{{ config_home }}/redshift.conf'

- name: Configure redshift service file
  template:
    src: redshift.service.j2
    dest: '{{ config_home }}/systemd/user/redshift.service'

- name: Enable redshift service
  systemd:
    name: redshift
    user: yes
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: '{{ user_xdg_runtime_dir }}'
    DBUS_SESSION_BUS_ADDRESS: '{{ user_dbus_session_bus_address }}'
