---
- name: Install redshift
  pacman:
    name: redshift
  become: true

- name: Configure redshift
  template:
    src: redshift.conf.j2
    dest: '{{ config_home }}/redshift.conf'

- name: Configure redshift service file
  template:
    src: redshift.service.j2
    dest: '{{ config_home }}/systemd/user/redshift.service'

- name: Enable and start redshift service
  systemd:
    name: redshift
    daemon-reload: yes
    user: yes
    enabled: yes
    state: started
