---
- name: install fish
  pacman:
    name: fish
    state: present
  become: true

- name: create fish config directory
  file:
    path: '{{ defaults.config_home }}/fish'
    state: directory

- include_tasks: universals.yml

- name: copy functions
  copy:
    src: functions
    dest: '{{ defaults.config_home }}/fish/'

- name: copy completions
  copy:
    src: completions
    dest: '{{ defaults.config_home }}/fish/'

- include_tasks: fisherman.yml
