---
- name: Install CUPS
  pacman:
    name: '{{ item }}'
  become: true
  loop:
    - cups
    - cups-pdf

- name: Add user '{{ username }}' to 'lpadmin' group
  user:
    name: '{{ username }}'
    groups: lpadmin
    append: yes

- name: Enable the services/sockets
  systemd:
    name: '{{ item }}'
    enabled: yes
  loop:
    - avahi-daemon.socket
    - org.cups.cupsd
