---
- name: Configure logind
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?{{ item.option }}='
    line: '{{ item.option }}={{ item.value }}'
  loop:
    - { option: 'HandlePowerKey', value: 'ignore' }
    - { option: 'HandleLidSwitch', value: 'suspend' }
    - { option: 'HandleLidSwitchDocked', value: 'suspend' }
