---
username: sweenu
user_password: '{{ vault_user_password }}'
email: brunoinec@gmail.com

root_password: '{{ vault_root_password }}'

timezone: Europe/Paris

language: en
territory: US
codeset: UTF-8
locale: '{{ language }}_{{ territory }}.{{ codeset }}'

keyboard:
  - layout: us
    variant: altgr-intl
  - layout: us
    variant: dvorak-alt-intl

hostname: carokann
profile_icon: prof_image.jpg
gtk_theme: Adapta-Nokto

defaults:
  config_home: '{{ ansible_user_dir }}/.config'
  data_home: '{{ ansible_user_dir }}/.local/share'
  cache_home: '{{ ansible_user_dir }}/.cache'

  desktop_dir: '{{ ansible_user_dir }}/Desktop'
  documents_dir: '{{ ansible_user_dir }}/Documents'
  download_dir: '{{ ansible_user_dir }}/Downloads'
  music_dir: '{{ ansible_user_dir }}/Music'
  pictures_dir: '{{ ansible_user_dir }}/Pictures'
  publicshare_dir: '{{ ansible_user_dir }}'
  repos_dir: '{{ ansible_user_dir }}/Repos'
  videos_dir: '{{ ansible_user_dir }}/Videos'

  editor: nvim
  sudo_editor: nvim
  visual: nvim
  pager: vimpager

  term: termite
  shell: fish
  browser: firefox
  printer: ENVY_4500
