---
- name: Install Xorg programs
  pacman:
    name: xorg-{{ item }}
  become: true
  loop:
    - server
    - xrandr

- name: Configure keyboard
  template:
    src: 10-keyboard.conf.j2
    dest: /etc/X11/xorg.conf.d/10-keyboard.conf
  become: true

- name: Configure touchpad
  template:
    src: 30-touchpad.conf.j2
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
  become: true
  when: ansible_form_factor == 'Laptop'

- include_tasks: compton.yml
