---
- name: Install qtile
  yaourt:
    name: qtile-python3-git

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become: true
  loop:
    - alsa-utils
    - python-iwlib
    - python-setproctitle

- name: Install config dependencies
  pacman:
    name: python-dbus, python-parse, feh
  become: true

- name: Install aur config dependencies
  yaourt:
    name: python-pynput

- name: Create qtile config directory
  file:
    path: '{{ config_home }}/qtile'
    state: directory

- name: Configure qtile
  template:
    src: '{{ item }}.py.j2'
    dest: '{{ config_home }}/qtile/{{ item }}.py'
  loop:
    - bars
    - config
    - keys
    - util
    - colors
    - widgets

- include_tasks: png-icons.yml
