---
- name: Check if Google Drive remote is already present
  command: grep 'type = drive' {{ config_home }}/rclone/rclone.conf
  register: gdrive
  changed_when: false
  ignore_errors: true

- name: Configure Google Drive
  command: rclone config create gdrive drive
  when: gdrive is failed

