---
- name: Install task
  pacman:
    name: task
  become: true

- name: Configure dunst
  template:
    src: taskrc.j2
    dest: '{{ ansible_user_dir }}/.taskrc'

- name: Configure Inthe.am
  copy:
    src: ./
    dest: '{{ defaults.data_home }}/task/'
    mode: 0600
