---
- name: Install ranger
  pacman:
    name: ranger
  become_user: root

- name: Install optional dependencies
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - atool
    - ffmpegthumbnailer
    - highlight
    - libcaca
    - mediainfo
    - odt2txt
    - poppler
    - python-chardet
    - w3m

- name: Create ranger config directory
  file:
    path: '{{ config_home }}/ranger'
    state: directory

- name: Configure ranger
  template:
    src: rc.conf.j2
    dest: '{{ config_home }}/ranger/rc.conf'
