---
# TODO: the 'when' statement is just a nasty quickfix to make the tasks idempotent,
# as it should
- name: Create boot partition
  parted:
    device: /dev/{{ disk }}
    name: EFI system partition
    number: 1
    part_start: 1MiB
    part_end: '{{ boot_partition_size }}'
    label: gpt
    flags: [ esp ]
    state: present
  when: ansible_devices[disk]['partitions'][boot_partition] not defined

- name: Create root partition
  parted:
    device: /dev/{{ disk }}
    name: '{{ root_partition_name }}'
    number: 2
    part_start: '{{ boot_partition_size }}'
    part_end: '{{ root_partition_size }}'
    label: gpt
    state: present
