---
- name: Install spotify
  yaourt:
    name: spotify

# To play local files
- name: Install zenity
  pacman:
    name: zenity
  become_user: root

- name: Install ffmpeg-compat-54
  yaourt:
    name: ffmpeg-compat-54

- import_tasks: spotifywm.yml
