---
- name: Install spotify
  yaourt:
    name: spotify

# To play local files
- name: Install zenity
  pacman:
    name: zenity
  become_user: root

- name: Import PGP signature for libavutil-52
  command: gpg --recv-keys {{ item }}
  when: item not in lookup('pipe', 'gpg -k --with-colons --homedir ' + user_dir + '/.gnupg')
  loop:
    - FCF986EA15E6E293A5644F10B4322F04D67658D8
  environment:
    HOME: '{{ user_dir }}'

- name: Install ffmpeg-compat-54
  yaourt:
    name: ffmpeg-compat-54

- import_tasks: spotifywm.yml
