---
- name: Set systemd timers to pause and resume notifications during church service
  copy:
    src: dunst-{{ item }}
    dest: '{{ defaults.config_home }}/systemd/user/'
  loop:
    - pause.timer
    - pause.service
    - resume.timer
    - resume.service

- name: Enable and start those timers
  systemd:
    name: dunst-{{ item }}.timer
    user: yes
    enabled: yes
    state: started
    daemon-reload: yes
  loop:
    - pause
    - resume
