---
- name: Set systemd timers to pause and resume notifications during church service
  copy:
    src: dunst-{{ item }}
    dest: '{{ config_home }}/systemd/user/'
  loop:
    - pause.timer
    - pause.service
    - resume.timer
    - resume.service

- name: Enable those timers
  systemd:
    name: dunst-{{ item }}.timer
    user: yes
    enabled: yes
  loop:
    - pause
    - resume
  environment:
    XDG_RUNTIME_DIR: '{{ user_xdg_runtime_dir }}'
    DBUS_SESSION_BUS_ADDRESS: '{{ user_dbus_session_bus_address }}' 
