---
- name: Set root's password
  user:
    name: root
    password: '{{ root_password |
    password_hash("sha512", 65534|random(seed=inventory_hostname)|string) }}'
  become_user: root

- name: Create user '{{ username }}'
  user:
    name: '{{ username }}'
    password: '{{ user_password |
    password_hash("sha512", 65534|random(seed=inventory_hostname)|string) }}'
    shell: /usr/bin/fish
    groups: [ wheel, adm ]
    append: yes
  become_user: root
