---
- name: Install every other programs
  pacman:
    name: '{{ item }}'
  become: true
  loop:
    - archiso
    - evince
    - fd
    - fwupd
    - fzf
    - gist
    - httpie
    - imagemagick
    - jupyter
    - musescore
    - ncdu
    - nmap
    - powertop
    - rustup
    - simple-scan
    - speedtest-cli
    - telegram-desktop
    - tig
    - tldr
    - trash-cli
    - tree
    - unrar
    - unzip
    - valgrind
    - vimpager
    - wget
    - whois
    - youtube-dl
    - zip

- name: Install every other programs in AUR
  yaourt:
    name: '{{ item }}'
  loop:
    - ddgr
    - discord
    - fkill
    - mons
    - pikaur
