---
- name: Install every other programs
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - archiso
    - evince
    - fd
    - fwupd
    - fzf
    - gist
    - htop
    - httpie
    - imagemagick
    - jupyter
    - musescore
    - ncdu
    - nmap
    - powertop
    - ripgrep
    - simple-scan
    - speedtest-cli
    - telegram-desktop
    - tig
    - tldr
    - trash-cli
    - tree
    - unrar
    - unzip
    - valgrind
    - wget
    - whois
    - youtube-dl
    - zip

- name: Import PGP signature for Discord
  command: gpg --recv-keys {{ item }}
  when: item not in lookup('pipe', 'gpg -k --with-colons')
  loop:
    - B6C8F98282B944E3B0D5C2530FC3042E345AD05D

- name: Install every other programs in AUR
  yaourt:
    name: '{{ item }}'
  loop:
    - bat
    - ddgr
    - discord
    - fkill
    - mons
    - pikaur
