---
- name: Install every other programs
  pacman:
    name: '{{ item }}'
  become: true
  loop:
    - archiso
    - docker
    - docker-compose
    - evince
    - fd
    - feh
    - firefox
    - fwupd
    - fzf
    - gist
    - imagemagick
    - jupyter
    - musescore
    - ncdu
    - nmap
    - powertop
    - ranger
    - rclone
    - rofi
    - rustup
    - sagemath
    - simple-scan
    - speedtest-cli
    - task
    - telegram-desktop
    - texlive-most
    - tig
    - tldr
    - trash-cli
    - tree
    - unrar
    - unzip
    - valgrind
    - vlc
    - wget
    - whois
    - youtube-dl
    - zip

- name: Install every other programs in AUR
  yaourt:
    name: '{{ item }}'
  loop:
    - alsi
    - canto-daemon
    - ddgr
    - discord
    - fkill
    - mons
    - openlp
    - pikaur
    - tunnelbear
