---
- name: Install every other programs
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - archiso
    - bat
    - bind-tools
    - fd
    - fwupd
    - fzf
    - gist
    - htop
    - httpie
    - imagemagick
    - man-db
    - mlocate
    - ncdu
    - nmap
    - powertop
    - ripgrep
    - speedtest-cli
    - telegram-desktop
    - tig
    - tldr
    - trash-cli
    - tree
    - unzip
    - wget
    - whois
    - xclip
    - youtube-dl
    - zip

# - name: Install every other programs in AUR
#   aur:
#     name: '{{ item }}'
#   loop:
#     - bitwarden-cli
#     - ddgr
#     - discord
#     - tor-browser
#     - standardnotes-desktop
