---
- name: Install every other programs
  pacman:
    name: '{{ item }}'
  become_user: root
  loop:
    - archiso
    - evince
    - fd
    - fwupd
    - fzf
    - gist
    - htop
    - httpie
    - imagemagick
    - jupyter
    - mlocate
    - musescore
    - ncdu
    - nmap
    - powertop
    - ripgrep
    - simple-scan
    - speedtest-cli
    - telegram-desktop
    - tig
    - tldr
    - trash-cli
    - tree
    - unrar
    - unzip
    - valgrind
    - vimpager
    - wget
    - whois
    - xclip
    - you-get
    - youtube-dl
    - zip

- name: Install every other programs in AUR
  yaourt:
    name: '{{ item }}'
  loop:
    - bat
    - bitwarden-cli
    - ddgr
    - discord
    - mons
