---
- name: Make sure the corrects hooks are used
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: 'HOOKS=(base systemd sd-plymouth autodetect
          {{ "keyboard sd-vconsole " if encrypted_root else ""}}modconf block
          {{ "sd-encrypt " if encrypted_root else ""}}filesystems fsck)'
  notify: Create initramfs image
