---
- name: Install indicator-kdeconnect
  yaourt:
    name: indicator-kdeconnect

- name: Configure indicator-kdeconnect service file
  template:
    src: indicator-kdeconnect.service.j2
    dest: '{{ config_home }}/systemd/user/indicator-kdeconnect.service'

- name: Check if UFW is used
  command: systemctl is-enabled ufw
  register: ufw_enabled
  changed_when: false

- name: Create KDEConnect app in ufw
  ini_file:
    path: /etc/ufw/applications.d/ufw-custom
    section: KDEConnect
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
  loop:
    - { option: title, value: KDEConnect }
    - { option: description, value: Computer-Phone communication }
    - { option: ports, value: '1714:1764/tcp|1714:1764/udp' }
  become_user: root

- name: Allow KDEConnect
  ufw:
    name: KDEConnect
    rule: allow
  when: ufw_enabled is succeeded
  become_user: root

- name: Enable indicator-kdeconnect service
  systemd:
    name: indicator-kdeconnect
    user: yes
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: '{{ user_xdg_runtime_dir }}'
    DBUS_SESSION_BUS_ADDRESS: '{{ user_dbus_session_bus_address }}'
