---
- name: Install lightdm
  pacman:
    name: lightdm
  become_user: root

- import_tasks: greeter.yml

- block:
    - name: Create 'autologin' group
      group:
        name: autologin
      become_user: root

    - name: Add '{{ username }}' to the 'autologin' group
      user:
        name: '{{ username }}'
        groups: autologin
        append: yes
      become_user: root
  when: autologin

- name: Configure lightdm
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
  become_user: root

- name: Enable lightdm service
  systemd:
    name: lightdm-plymouth
    enabled: yes
  become_user: root
