---
- name: Install lightdm
  pacman:
    name: lightdm

- import_tasks: greeter.yml

- name: Configure lightdm
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf

- name: Enable lightdm service
  systemd:
    name: lightdm-plymouth
    enabled: yes

