---
- block:
    - name: Set the timezone
      timezone:
        name: '{{ timezone }}'
  rescue:
    - name: Set the timezone manually
      file:
        src: /usr/share/zoneinfo/{{ timezone }}
        path: /etc/localtime
        state: link

- name: Synchromize hwclock with sysclock
  command: hwclock --systohc
  args:
    creates: /etc/adjtime
