---
- name: Install xdg-user-dirs
  pacman:
    name: xdg-user-dirs
  become: true

- name: Configure user-dirs
  template:
    src: user-dirs.dirs.j2
    dest: '{{ defaults.config_home }}/user-dirs.dirs'
  notify:
    - Update xdg-user-dirs

- meta: flush_handlers
