- name: Install NeoVim
  pacman:
    name: neovim
  become: true

- name: Install optional dependencies
  pacman:
    name: python-neovim
  become: true

- name: Create configuration directory
  file:
    path: '{{ config_home }}/nvim'
    state: directory

- name: Configure NeoVim
  template:
    src: init.vim.j2
    dest: '{{ config_home }}/nvim/init.vim'
  notify: Install plugins

- include_tasks: vim-plug.yml
