---
- name: Install acpilight
  yaourt:
    name: acpilight

- name: Configure a udev rule for users in 'video' group to use acpilight
  template:
    src: 90-backlight.rules.j2
    dest: /etc/udev/rules.d/90-backlight.rules

- name: Add user '{{ username }}' to 'video' group
  user:
    name: '{{ username }}'
    groups: video
    append: yes
