---
- name: Enable multilib repositories
  ini_file:
    path: /etc/pacman.conf
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist
  become_user: root
  notify: Update pacman cache

- meta: flush_handlers

- name: Install Lutris
  yaourt:
    name: lutris

# https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell
- name: Get out of Wine dependency hell
  pacman:
    name: wine-staging, {{ dependency_hell }}
  become_user: root

# - name: Part2
#   pacman:
#     name: '{{ item }}'
#   become_user: root
#   loop:
#     - opencl-icd-loader
#     - lib32-opencl-icd-loader

- import_tasks: blizzard.yml
